version: '3'

services:
  mysql-database:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - phpmyadmin_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-database
      PMA_USER: root
      PMA_PASSWORD: root@123
    networks:
      - phpmyadmin_network
    depends_on:
      - mysql-database

networks:
  phpmyadmin_network:
    driver: bridge  # Define a rede como bridge para ser criada automaticamente